services:
  {SERVICE}:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 22
    restart: unless-stopped
    environment:
      - DISPLAY=unix$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./src:{PROJECT_DIR}
   
